using System.Data;
using System.Text.Json;
using Microsoft.Data.SqlClient;
using NexoERP.Api.Data;

namespace NexoERP.Api.AdvancedControls;

public sealed class AdvancedControlsRepository(TenantConnectionFactory connections)
{
    public async Task<IReadOnlyList<CostConceptResponse>> GetCostConceptsAsync(long e,CancellationToken ct)
    {
        await using var c=await connections.OpenAsync(e,false,ct);await using var q=c.CreateCommand();q.CommandText="SELECT ConceptoCostoId,Codigo,Nombre,Tratamiento,MetodoDistribucionDefecto,RequiereDocumentoSoporte FROM cost.ConceptoCostoAdquisicion WHERE EmpresaId=@E AND Activo=1 ORDER BY Nombre;";Add(q,"@E",SqlDbType.BigInt,e);await using var r=await q.ExecuteReaderAsync(ct);var rows=new List<CostConceptResponse>();while(await r.ReadAsync(ct))rows.Add(new(r.GetInt64(0),r.GetString(1),r.GetString(2),r.GetString(3),r.IsDBNull(4)?null:r.GetString(4),r.GetBoolean(5)));return rows;
    }

    public async Task<IReadOnlyList<LandedCostSourceResponse>> GetLandedCostSourcesAsync(long e,string? search,CancellationToken ct)
    {
        await using var c=await connections.OpenAsync(e,false,ct);await using var q=c.CreateCommand();q.CommandText="""
            SELECT l.RecepcionMercanciaLineaId,h.Numero,t.RazonSocial,h.TerceroId,h.FechaContable,l.ArticuloId,a.Codigo,a.Descripcion,l.CantidadBase,l.CostoTotalCapitalizable,l.CostoAdicionalAsignado
            FROM inv.RecepcionMercanciaLinea l JOIN inv.RecepcionMercancia h ON h.EmpresaId=l.EmpresaId AND h.RecepcionMercanciaId=l.RecepcionMercanciaId JOIN ter.Tercero t ON t.EmpresaId=h.EmpresaId AND t.TerceroId=h.TerceroId JOIN inv.Articulo a ON a.EmpresaId=l.EmpresaId AND a.ArticuloId=l.ArticuloId
            WHERE l.EmpresaId=@E AND h.Estado IN('VALIDADA','CONTABILIZADA') AND (@Q IS NULL OR h.Numero LIKE '%'+@Q+'%' OR t.RazonSocial LIKE '%'+@Q+'%' OR a.Codigo LIKE '%'+@Q+'%' OR a.Descripcion LIKE '%'+@Q+'%') ORDER BY h.FechaContable DESC,h.Numero,l.NumeroLinea;
            """;Add(q,"@E",SqlDbType.BigInt,e);Add(q,"@Q",SqlDbType.NVarChar,string.IsNullOrWhiteSpace(search)?null:search.Trim(),120);await using var r=await q.ExecuteReaderAsync(ct);var rows=new List<LandedCostSourceResponse>();while(await r.ReadAsync(ct))rows.Add(new(r.GetInt64(0),r.GetString(1),r.GetString(2),r.GetInt64(3),DateOnly.FromDateTime(r.GetDateTime(4)),r.GetInt64(5),r.GetString(6),r.GetString(7),r.GetDecimal(8),r.GetDecimal(9),r.GetDecimal(10)));return rows;
    }

    public async Task<IReadOnlyList<LandedCostListResponse>> GetLandedCostsAsync(long e,CancellationToken ct)
    {
        await using var c=await connections.OpenAsync(e,false,ct);await using var q=c.CreateCommand();q.CommandText="""
            SELECT d.DistribucionCostoId,dc.NumeroSoporte,cc.Nombre,t.RazonSocial,dc.FechaDocumento,d.Metodo,d.ValorTotal,d.Estado,COUNT(l.DistribucionCostoLineaId),d.AplicadaEnUtc
            FROM cost.DistribucionCosto d JOIN cost.DocumentoCostoAdquisicion dc ON dc.EmpresaId=d.EmpresaId AND dc.DocumentoCostoId=d.DocumentoCostoId JOIN cost.ConceptoCostoAdquisicion cc ON cc.EmpresaId=dc.EmpresaId AND cc.ConceptoCostoId=dc.ConceptoCostoId JOIN ter.Tercero t ON t.EmpresaId=dc.EmpresaId AND t.TerceroId=dc.TerceroId LEFT JOIN cost.DistribucionCostoLinea l ON l.EmpresaId=d.EmpresaId AND l.DistribucionCostoId=d.DistribucionCostoId
            WHERE d.EmpresaId=@E GROUP BY d.DistribucionCostoId,dc.NumeroSoporte,cc.Nombre,t.RazonSocial,dc.FechaDocumento,d.Metodo,d.ValorTotal,d.Estado,d.AplicadaEnUtc ORDER BY d.DistribucionCostoId DESC;
            """;Add(q,"@E",SqlDbType.BigInt,e);await using var r=await q.ExecuteReaderAsync(ct);var rows=new List<LandedCostListResponse>();while(await r.ReadAsync(ct))rows.Add(new(r.GetInt64(0),r.GetString(1),r.GetString(2),r.GetString(3),DateOnly.FromDateTime(r.GetDateTime(4)),r.GetString(5),r.GetDecimal(6),r.GetString(7),r.GetInt32(8),r.IsDBNull(9)?null:r.GetDateTime(9)));return rows;
    }

    public async Task<CreatedLandedCostResponse> CreateLandedCostAsync(long e,CreateLandedCostRequest input,CancellationToken ct)
    {
        await using var c=await connections.OpenAsync(e,false,ct);await using var tx=(SqlTransaction)await c.BeginTransactionAsync(ct);
        await using(var find=c.CreateCommand()){find.Transaction=tx;find.CommandText="SELECT dc.DocumentoCostoId,d.DistribucionCostoId,d.Estado FROM cost.DocumentoCostoAdquisicion dc JOIN cost.DistribucionCosto d ON d.EmpresaId=dc.EmpresaId AND d.DocumentoCostoId=dc.DocumentoCostoId WHERE dc.EmpresaId=@E AND dc.TerceroId=@T AND dc.NumeroSoporte=@N AND dc.ConceptoCostoId=@C;";Add(find,"@E",SqlDbType.BigInt,e);Add(find,"@T",SqlDbType.BigInt,input.TerceroId);Add(find,"@N",SqlDbType.NVarChar,input.NumeroSoporte.Trim(),50);Add(find,"@C",SqlDbType.BigInt,input.ConceptoCostoId);await using var found=await find.ExecuteReaderAsync(ct);if(await found.ReadAsync(ct)){var response=new CreatedLandedCostResponse(found.GetInt64(0),found.GetInt64(1),found.GetString(2),true);await found.DisposeAsync();await tx.RollbackAsync(ct);return response;}}
        long documentId;await using(var q=c.CreateCommand()){q.Transaction=tx;q.CommandText="INSERT cost.DocumentoCostoAdquisicion(EmpresaId,ConceptoCostoId,TerceroId,NumeroSoporte,FechaDocumento,Moneda,ValorDistribuible,Estado,CreadoPorUsuarioId) OUTPUT inserted.DocumentoCostoId VALUES(@E,@C,@T,@N,@F,@M,@V,'CALCULADO',@U);";Add(q,"@E",SqlDbType.BigInt,e);Add(q,"@C",SqlDbType.BigInt,input.ConceptoCostoId);Add(q,"@T",SqlDbType.BigInt,input.TerceroId);Add(q,"@N",SqlDbType.NVarChar,input.NumeroSoporte.Trim(),50);Add(q,"@F",SqlDbType.Date,input.FechaDocumento.ToDateTime(TimeOnly.MinValue));Add(q,"@M",SqlDbType.Char,input.Moneda.Trim().ToUpperInvariant(),3);AddDecimal(q,"@V",input.ValorDistribuible,20,4);Add(q,"@U",SqlDbType.BigInt,input.UsuarioId);documentId=Convert.ToInt64(await q.ExecuteScalarAsync(ct));}
        long distributionId;await using(var q=c.CreateCommand()){q.Transaction=tx;q.CommandText="INSERT cost.DistribucionCosto(EmpresaId,DocumentoCostoId,Metodo,ValorTotal,BaseTotal,Estado,CalculadaPorUsuarioId) OUTPUT inserted.DistribucionCostoId VALUES(@E,@D,@M,@V,0,'CALCULADA',@U);";Add(q,"@E",SqlDbType.BigInt,e);Add(q,"@D",SqlDbType.BigInt,documentId);Add(q,"@M",SqlDbType.VarChar,input.Metodo,25);AddDecimal(q,"@V",input.ValorDistribuible,20,4);Add(q,"@U",SqlDbType.BigInt,input.UsuarioId);distributionId=Convert.ToInt64(await q.ExecuteScalarAsync(ct));}
        foreach(var line in input.Lineas){await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="INSERT cost.DistribucionCostoObjetivo(EmpresaId,DistribucionCostoId,RecepcionMercanciaLineaId,BaseManual,PorcentajeManual,ValorManual) VALUES(@E,@D,@R,@B,@P,@V);";Add(q,"@E",SqlDbType.BigInt,e);Add(q,"@D",SqlDbType.BigInt,distributionId);Add(q,"@R",SqlDbType.BigInt,line.RecepcionMercanciaLineaId);AddDecimalNullable(q,"@B",line.BaseManual,28,10);AddDecimalNullable(q,"@P",line.PorcentajeManual,12,8);AddDecimalNullable(q,"@V",line.ValorManual,20,4);await q.ExecuteNonQueryAsync(ct);}await tx.CommitAsync(ct);
        await using(var q=c.CreateCommand()){q.CommandType=CommandType.StoredProcedure;q.CommandText="cost.usp_CalcularDistribucionCosto";Add(q,"@EmpresaId",SqlDbType.BigInt,e);Add(q,"@DistribucionCostoId",SqlDbType.BigInt,distributionId);Add(q,"@UsuarioId",SqlDbType.BigInt,input.UsuarioId);await q.ExecuteNonQueryAsync(ct);}return new(documentId,distributionId,"CALCULADA",false);
    }

    public async Task<IReadOnlyList<CostBookResponse>> GetCostBooksAsync(long e,CancellationToken ct){await using var c=await connections.OpenAsync(e,false,ct);await using var q=c.CreateCommand();q.CommandText="SELECT LibroCostoId,Codigo,Nombre,Categoria,FormulaValoracion,EsPrincipal,Estado FROM cost.LibroCosto WHERE EmpresaId=@E ORDER BY EsPrincipal DESC,Nombre;";Add(q,"@E",SqlDbType.BigInt,e);await using var r=await q.ExecuteReaderAsync(ct);var rows=new List<CostBookResponse>();while(await r.ReadAsync(ct))rows.Add(new(r.GetInt64(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetBoolean(5),r.GetString(6)));return rows;}
    public async Task<CostBookResponse> CreateCostBookAsync(long e,CreateCostBookRequest input,CancellationToken ct){await using var c=await connections.OpenAsync(e,false,ct);await using var q=c.CreateCommand();q.CommandText="INSERT cost.LibroCosto(EmpresaId,Codigo,Nombre,Categoria,FormulaValoracion,EsPrincipal,Estado) OUTPUT inserted.LibroCostoId,inserted.Codigo,inserted.Nombre,inserted.Categoria,inserted.FormulaValoracion,inserted.EsPrincipal,inserted.Estado VALUES(@E,@C,@N,@Cat,@F,@P,'ACTIVO');";Add(q,"@E",SqlDbType.BigInt,e);Add(q,"@C",SqlDbType.NVarChar,input.Codigo.Trim().ToUpperInvariant(),30);Add(q,"@N",SqlDbType.NVarChar,input.Nombre.Trim(),120);Add(q,"@Cat",SqlDbType.VarChar,input.Categoria,15);Add(q,"@F",SqlDbType.VarChar,input.FormulaValoracion,30);Add(q,"@P",SqlDbType.Bit,input.EsPrincipal);await using var r=await q.ExecuteReaderAsync(ct);await r.ReadAsync(ct);return new(r.GetInt64(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetBoolean(5),r.GetString(6));}
    public async Task<IReadOnlyList<InventoryGroupResponse>> GetInventoryGroupsAsync(long e,CancellationToken ct){await using var c=await connections.OpenAsync(e,false,ct);await using var q=c.CreateCommand();q.CommandText="SELECT GrupoInventarioId,Codigo,Nombre,NaturalezaUso FROM inv.GrupoInventario WHERE EmpresaId=@E AND Activo=1 ORDER BY Nombre;";Add(q,"@E",SqlDbType.BigInt,e);await using var r=await q.ExecuteReaderAsync(ct);var rows=new List<InventoryGroupResponse>();while(await r.ReadAsync(ct))rows.Add(new(r.GetInt64(0),r.GetString(1),r.GetString(2),r.GetString(3)));return rows;}
    public async Task<InventoryGroupResponse> CreateInventoryGroupAsync(long e,CreateInventoryGroupRequest input,CancellationToken ct){await using var c=await connections.OpenAsync(e,false,ct);await using var q=c.CreateCommand();q.CommandText="INSERT inv.GrupoInventario(EmpresaId,Codigo,Nombre,NaturalezaUso) OUTPUT inserted.GrupoInventarioId,inserted.Codigo,inserted.Nombre,inserted.NaturalezaUso VALUES(@E,@C,@N,@U);";Add(q,"@E",SqlDbType.BigInt,e);Add(q,"@C",SqlDbType.NVarChar,input.Codigo.Trim().ToUpperInvariant(),30);Add(q,"@N",SqlDbType.NVarChar,input.Nombre.Trim(),120);Add(q,"@U",SqlDbType.NVarChar,input.NaturalezaUso.Trim(),120);await using var r=await q.ExecuteReaderAsync(ct);await r.ReadAsync(ct);return new(r.GetInt64(0),r.GetString(1),r.GetString(2),r.GetString(3));}
    public async Task<IReadOnlyList<CostPolicyResponse>> GetCostPoliciesAsync(long e,CancellationToken ct){await using var c=await connections.OpenAsync(e,false,ct);await using var q=c.CreateCommand();q.CommandText="SELECT p.PoliticaValoracionGrupoId,p.LibroCostoId,l.Nombre,p.GrupoInventarioId,g.Nombre,p.FormulaValoracion,p.VigenteDesde,p.VigenteHasta,p.MotivoCambio FROM cost.PoliticaValoracionGrupo p JOIN cost.LibroCosto l ON l.EmpresaId=p.EmpresaId AND l.LibroCostoId=p.LibroCostoId JOIN inv.GrupoInventario g ON g.EmpresaId=p.EmpresaId AND g.GrupoInventarioId=p.GrupoInventarioId WHERE p.EmpresaId=@E ORDER BY p.VigenteDesde DESC;";Add(q,"@E",SqlDbType.BigInt,e);await using var r=await q.ExecuteReaderAsync(ct);var rows=new List<CostPolicyResponse>();while(await r.ReadAsync(ct))rows.Add(new(r.GetInt64(0),r.GetInt64(1),r.GetString(2),r.GetInt64(3),r.GetString(4),r.GetString(5),DateOnly.FromDateTime(r.GetDateTime(6)),r.IsDBNull(7)?null:DateOnly.FromDateTime(r.GetDateTime(7)),r.IsDBNull(8)?null:r.GetString(8)));return rows;}
    public async Task<CostPolicyResponse> SaveCostPolicyAsync(long e,SaveCostPolicyRequest input,CancellationToken ct){await using var c=await connections.OpenAsync(e,false,ct);await using var q=c.CreateCommand();q.CommandText="INSERT cost.PoliticaValoracionGrupo(EmpresaId,LibroCostoId,GrupoInventarioId,FormulaValoracion,VigenteDesde,VigenteHasta,MotivoCambio,AprobadoPorUsuarioId) OUTPUT inserted.PoliticaValoracionGrupoId VALUES(@E,@L,@G,@F,@D,@H,@M,@U);";Add(q,"@E",SqlDbType.BigInt,e);Add(q,"@L",SqlDbType.BigInt,input.LibroCostoId);Add(q,"@G",SqlDbType.BigInt,input.GrupoInventarioId);Add(q,"@F",SqlDbType.VarChar,input.FormulaValoracion,30);Add(q,"@D",SqlDbType.Date,input.VigenteDesde.ToDateTime(TimeOnly.MinValue));Add(q,"@H",SqlDbType.Date,input.VigenteHasta?.ToDateTime(TimeOnly.MinValue));Add(q,"@M",SqlDbType.NVarChar,input.MotivoCambio,500);Add(q,"@U",SqlDbType.BigInt,input.UsuarioId);var id=Convert.ToInt64(await q.ExecuteScalarAsync(ct));var books=await GetCostPoliciesAsync(e,ct);return books.Single(x=>x.PoliticaValoracionGrupoId==id);}
    public async Task<IReadOnlyList<CostBookBalanceResponse>> GetCostBookBalancesAsync(long e,long? bookId,CancellationToken ct){await using var c=await connections.OpenAsync(e,false,ct);await using var q=c.CreateCommand();q.CommandText="SELECT s.LibroCostoId,l.Nombre,s.BodegaId,b.Nombre,s.ArticuloId,a.Codigo,a.Descripcion,s.Existencia,s.CostoUnitario,s.ValorTotal FROM cost.SaldoCostoLibroBodega s JOIN cost.LibroCosto l ON l.EmpresaId=s.EmpresaId AND l.LibroCostoId=s.LibroCostoId JOIN inv.Bodega b ON b.EmpresaId=s.EmpresaId AND b.BodegaId=s.BodegaId JOIN inv.Articulo a ON a.EmpresaId=s.EmpresaId AND a.ArticuloId=s.ArticuloId WHERE s.EmpresaId=@E AND (@L IS NULL OR s.LibroCostoId=@L) ORDER BY l.Nombre,b.Nombre,a.Codigo;";Add(q,"@E",SqlDbType.BigInt,e);Add(q,"@L",SqlDbType.BigInt,bookId);await using var r=await q.ExecuteReaderAsync(ct);var rows=new List<CostBookBalanceResponse>();while(await r.ReadAsync(ct))rows.Add(new(r.GetInt64(0),r.GetString(1),r.GetInt64(2),r.GetString(3),r.GetInt64(4),r.GetString(5),r.GetString(6),r.GetDecimal(7),r.GetDecimal(8),r.GetDecimal(9)));return rows;}

    public async Task<IReadOnlyList<InventoryNetValueResponse>> GetNetValuesAsync(long e,CancellationToken ct){await using var c=await connections.OpenAsync(e,false,ct);await using var q=c.CreateCommand();q.CommandText="SELECT v.BodegaId,b.Nombre,v.ArticuloId,a.Codigo,a.Descripcion,v.Existencia,v.CostoHistorico,v.DeterioroAcumulado,v.ValorNetoContable FROM inv.vw_ValorNetoInventario v JOIN inv.Bodega b ON b.EmpresaId=v.EmpresaId AND b.BodegaId=v.BodegaId JOIN inv.Articulo a ON a.EmpresaId=v.EmpresaId AND a.ArticuloId=v.ArticuloId WHERE v.EmpresaId=@E ORDER BY b.Nombre,a.Codigo;";Add(q,"@E",SqlDbType.BigInt,e);await using var r=await q.ExecuteReaderAsync(ct);var rows=new List<InventoryNetValueResponse>();while(await r.ReadAsync(ct))rows.Add(new(r.GetInt64(0),r.GetString(1),r.GetInt64(2),r.GetString(3),r.GetString(4),r.GetDecimal(5),r.GetDecimal(6),r.GetDecimal(7),r.GetDecimal(8)));return rows;}
    public async Task<IReadOnlyList<ImpairmentListResponse>> GetImpairmentsAsync(long e,CancellationToken ct){await using var c=await connections.OpenAsync(e,false,ct);await using var q=c.CreateCommand();q.CommandText="SELECT d.DeterioroInventarioId,d.CreadoEnUtc,d.Tipo,b.Nombre,a.Codigo,a.Descripcion,d.CostoHistorico,d.ValorDeterioro,d.SaldoDeterioroPosterior,d.CostoHistorico-d.SaldoDeterioroPosterior,d.Motivo,d.DocumentoSoporte FROM inv.DeterioroInventario d JOIN inv.Bodega b ON b.EmpresaId=d.EmpresaId AND b.BodegaId=d.BodegaId JOIN inv.Articulo a ON a.EmpresaId=d.EmpresaId AND a.ArticuloId=d.ArticuloId WHERE d.EmpresaId=@E ORDER BY d.DeterioroInventarioId DESC;";Add(q,"@E",SqlDbType.BigInt,e);await using var r=await q.ExecuteReaderAsync(ct);var rows=new List<ImpairmentListResponse>();while(await r.ReadAsync(ct))rows.Add(new(r.GetInt64(0),r.GetDateTime(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetDecimal(6),r.GetDecimal(7),r.GetDecimal(8),r.GetDecimal(9),r.GetString(10),r.IsDBNull(11)?null:r.GetString(11)));return rows;}
    public async Task<IReadOnlyList<NegativeExceptionListResponse>> GetNegativeExceptionsAsync(long e,CancellationToken ct){await using var c=await connections.OpenAsync(e,false,ct);await using var q=c.CreateCommand();q.CommandText="SELECT n.SalidaExcepcionalNegativaId,n.NumeroDocumento,b.Nombre,a.Codigo,a.Descripcion,n.CantidadSolicitada,n.CantidadValorizada,n.CantidadPendiente,n.Estado,n.Motivo,n.CreadoEnUtc FROM inv.SalidaExcepcionalNegativa n JOIN inv.Bodega b ON b.EmpresaId=n.EmpresaId AND b.BodegaId=n.BodegaId JOIN inv.Articulo a ON a.EmpresaId=n.EmpresaId AND a.ArticuloId=n.ArticuloId WHERE n.EmpresaId=@E ORDER BY n.SalidaExcepcionalNegativaId DESC;";Add(q,"@E",SqlDbType.BigInt,e);await using var r=await q.ExecuteReaderAsync(ct);var rows=new List<NegativeExceptionListResponse>();while(await r.ReadAsync(ct))rows.Add(new(r.GetInt64(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetDecimal(5),r.GetDecimal(6),r.GetDecimal(7),r.GetString(8),r.GetString(9),r.GetDateTime(10)));return rows;}
    public async Task<IReadOnlyList<NegativeRegularizationSourceResponse>> GetNegativeSourcesAsync(long e,long exceptionId,CancellationToken ct){await using var c=await connections.OpenAsync(e,false,ct);await using var q=c.CreateCommand();q.CommandText="""
        SELECT r.RecepcionMercanciaLineaId,h.Numero,h.BodegaId,r.ArticuloId,a.Codigo,a.Descripcion,s.CantidadDisponible,CAST(r.CostoTotalCapitalizable/r.CantidadBase AS decimal(20,8))
        FROM inv.SalidaExcepcionalNegativa n JOIN inv.RecepcionMercanciaLinea r ON r.EmpresaId=n.EmpresaId AND r.ArticuloId=n.ArticuloId JOIN inv.RecepcionMercancia h ON h.EmpresaId=r.EmpresaId AND h.RecepcionMercanciaId=r.RecepcionMercanciaId AND h.BodegaId=n.BodegaId AND h.Estado='CONTABILIZADA' JOIN inv.Articulo a ON a.EmpresaId=r.EmpresaId AND a.ArticuloId=r.ArticuloId JOIN inv.OrigenInventario o ON o.EmpresaId=r.EmpresaId AND o.RecepcionMercanciaLineaId=r.RecepcionMercanciaLineaId JOIN inv.SaldoOrigenBodega s ON s.EmpresaId=o.EmpresaId AND s.OrigenInventarioId=o.OrigenInventarioId AND s.BodegaId=h.BodegaId
        WHERE n.EmpresaId=@E AND n.SalidaExcepcionalNegativaId=@N AND s.CantidadDisponible>=n.CantidadPendiente ORDER BY h.FechaContable DESC;
        """;Add(q,"@E",SqlDbType.BigInt,e);Add(q,"@N",SqlDbType.BigInt,exceptionId);await using var r=await q.ExecuteReaderAsync(ct);var rows=new List<NegativeRegularizationSourceResponse>();while(await r.ReadAsync(ct))rows.Add(new(r.GetInt64(0),r.GetString(1),r.GetInt64(2),r.GetInt64(3),r.GetString(4),r.GetString(5),r.GetDecimal(6),r.GetDecimal(7)));return rows;}

    public async Task<IReadOnlyList<PhysicalCountListResponse>> GetPhysicalCountsAsync(long e,CancellationToken ct){await using var c=await connections.OpenAsync(e,false,ct);await using var q=c.CreateCommand();q.CommandText="SELECT h.ConteoFisicoId,h.Numero,h.BodegaId,b.Nombre,h.FechaCorte,h.Estado,COUNT(DISTINCT l.ConteoFisicoLineaId),COUNT(c.ConteoCapturaId),COALESCE(SUM(DISTINCT ABS(l.DiferenciaAprobada)),0) FROM inv.ConteoFisico h JOIN inv.Bodega b ON b.EmpresaId=h.EmpresaId AND b.BodegaId=h.BodegaId LEFT JOIN inv.ConteoFisicoLinea l ON l.EmpresaId=h.EmpresaId AND l.ConteoFisicoId=h.ConteoFisicoId LEFT JOIN inv.ConteoCaptura c ON c.EmpresaId=l.EmpresaId AND c.ConteoFisicoLineaId=l.ConteoFisicoLineaId WHERE h.EmpresaId=@E GROUP BY h.ConteoFisicoId,h.Numero,h.BodegaId,b.Nombre,h.FechaCorte,h.Estado ORDER BY h.ConteoFisicoId DESC;";Add(q,"@E",SqlDbType.BigInt,e);await using var r=await q.ExecuteReaderAsync(ct);var rows=new List<PhysicalCountListResponse>();while(await r.ReadAsync(ct))rows.Add(new(r.GetInt64(0),r.GetString(1),r.GetInt64(2),r.GetString(3),r.GetDateTime(4),r.GetString(5),r.GetInt32(6),r.GetInt32(7),r.GetDecimal(8)));return rows;}
    public async Task<IReadOnlyList<PhysicalCountLineResponse>> GetPhysicalCountLinesAsync(long e,long id,CancellationToken ct){await using var c=await connections.OpenAsync(e,false,ct);await using var q=c.CreateCommand();q.CommandText="SELECT l.ConteoFisicoLineaId,l.ArticuloId,a.Codigo,a.Descripcion,u.Codigo,lot.NumeroLote,l.ExistenciaTeorica,x.NumeroConteo,x.CantidadContada,l.CantidadAprobada,l.DiferenciaAprobada FROM inv.ConteoFisicoLinea l JOIN inv.Articulo a ON a.EmpresaId=l.EmpresaId AND a.ArticuloId=l.ArticuloId LEFT JOIN inv.Ubicacion u ON u.EmpresaId=l.EmpresaId AND u.UbicacionId=l.UbicacionId LEFT JOIN inv.Lote lot ON lot.EmpresaId=l.EmpresaId AND lot.LoteId=l.LoteId OUTER APPLY(SELECT TOP(1)c.NumeroConteo,c.CantidadContada FROM inv.ConteoCaptura c WHERE c.EmpresaId=l.EmpresaId AND c.ConteoFisicoLineaId=l.ConteoFisicoLineaId ORDER BY c.NumeroConteo DESC,c.ConteoCapturaId DESC)x WHERE l.EmpresaId=@E AND l.ConteoFisicoId=@I ORDER BY a.Codigo;";Add(q,"@E",SqlDbType.BigInt,e);Add(q,"@I",SqlDbType.BigInt,id);await using var r=await q.ExecuteReaderAsync(ct);var rows=new List<PhysicalCountLineResponse>();while(await r.ReadAsync(ct))rows.Add(new(r.GetInt64(0),r.GetInt64(1),r.GetString(2),r.GetString(3),r.IsDBNull(4)?null:r.GetString(4),r.IsDBNull(5)?null:r.GetString(5),r.GetDecimal(6),r.IsDBNull(7)?null:r.GetInt16(7),r.IsDBNull(8)?null:r.GetDecimal(8),r.IsDBNull(9)?null:r.GetDecimal(9),r.IsDBNull(10)?null:r.GetDecimal(10)));return rows;}
    public async Task<CountStateResponse> CreatePhysicalCountAsync(long e,CreatePhysicalCountRequest input,CancellationToken ct){await using var c=await connections.OpenAsync(e,false,ct);await using var q=c.CreateCommand();q.CommandText="SELECT ConteoFisicoId,Estado FROM inv.ConteoFisico WHERE EmpresaId=@E AND Numero=@N;";Add(q,"@E",SqlDbType.BigInt,e);Add(q,"@N",SqlDbType.NVarChar,input.Numero.Trim(),50);await using(var r=await q.ExecuteReaderAsync(ct)){if(await r.ReadAsync(ct))return new(r.GetInt64(0),r.GetString(1),true);}q.Parameters.Clear();q.CommandText="INSERT inv.ConteoFisico(EmpresaId,Numero,BodegaId,FechaCorte,CreadoPorUsuarioId) OUTPUT inserted.ConteoFisicoId VALUES(@E,@N,@B,@F,@U);";Add(q,"@E",SqlDbType.BigInt,e);Add(q,"@N",SqlDbType.NVarChar,input.Numero.Trim(),50);Add(q,"@B",SqlDbType.BigInt,input.BodegaId);Add(q,"@F",SqlDbType.DateTime2,input.FechaCorte);Add(q,"@U",SqlDbType.BigInt,input.UsuarioId);return new(Convert.ToInt64(await q.ExecuteScalarAsync(ct)),"PREPARACION",false);}
    public Task<CountStateResponse> StartPhysicalCountAsync(long e,long id,long? user,CancellationToken ct)=>ExecuteCountProcedureAsync(e,id,"inv.usp_IniciarConteoFisico",user,null,ct);
    public Task<CountStateResponse> ReviewPhysicalCountAsync(long e,long id,long? user,CancellationToken ct)=>ExecuteCountProcedureAsync(e,id,"inv.usp_EnviarConteoRevision",user,null,ct);
    public async Task<CountStateResponse> ApprovePhysicalCountAsync(long e,long id,ApprovePhysicalCountRequest input,CancellationToken ct)=>await ExecuteCountProcedureAsync(e,id,"inv.usp_AprobarConteoFisico",input.UsuarioId,JsonSerializer.Serialize(input.Lineas.Select(x=>new{conteoFisicoLineaId=x.ConteoFisicoLineaId,cantidadAprobada=x.CantidadAprobada})),ct);
    public async Task CaptureCountAsync(long e,long lineId,CaptureCountRequest input,CancellationToken ct){await using var c=await connections.OpenAsync(e,false,ct);await using var q=c.CreateCommand();q.CommandText="IF NOT EXISTS(SELECT 1 FROM inv.ConteoFisicoLinea l JOIN inv.ConteoFisico h ON h.EmpresaId=l.EmpresaId AND h.ConteoFisicoId=l.ConteoFisicoId WHERE l.EmpresaId=@E AND l.ConteoFisicoLineaId=@L AND h.Estado IN('EN_CONTEO','RECONTEO')) THROW 51993,'La linea no esta habilitada para captura.',1; INSERT inv.ConteoCaptura(EmpresaId,ConteoFisicoLineaId,NumeroConteo,CantidadContada,UsuarioId) VALUES(@E,@L,@N,@C,@U);";Add(q,"@E",SqlDbType.BigInt,e);Add(q,"@L",SqlDbType.BigInt,lineId);Add(q,"@N",SqlDbType.SmallInt,input.NumeroConteo);AddDecimal(q,"@C",input.CantidadContada,20,6);Add(q,"@U",SqlDbType.BigInt,input.UsuarioId);await q.ExecuteNonQueryAsync(ct);}

    public async Task<IReadOnlyList<AdvancedInventoryPeriodResponse>> GetPeriodsAsync(long e,CancellationToken ct){await using var c=await connections.OpenAsync(e,false,ct);await using var q=c.CreateCommand();q.CommandText="SELECT PeriodoInventarioId,Codigo,FechaInicio,FechaFin,Estado,CerradoEnUtc,VersionCierre FROM core.PeriodoInventario WHERE EmpresaId=@E ORDER BY FechaInicio DESC;";Add(q,"@E",SqlDbType.BigInt,e);await using var r=await q.ExecuteReaderAsync(ct);var rows=new List<AdvancedInventoryPeriodResponse>();while(await r.ReadAsync(ct))rows.Add(new(r.GetInt64(0),r.GetString(1),DateOnly.FromDateTime(r.GetDateTime(2)),DateOnly.FromDateTime(r.GetDateTime(3)),r.GetString(4),r.IsDBNull(5)?null:r.GetDateTime(5),r.IsDBNull(6)?null:r.GetInt32(6)));return rows;}
    public async Task<IReadOnlyList<ReconciliationListResponse>> GetReconciliationsAsync(long e,CancellationToken ct){await using var c=await connections.OpenAsync(e,false,ct);await using var q=c.CreateCommand();q.CommandText="SELECT r.ReconciliacionInventarioId,r.Estado,r.Diferencias,b.Nombre,a.Codigo,r.FinalizadaEnUtc FROM inv.ReconciliacionInventario r LEFT JOIN inv.Bodega b ON b.EmpresaId=r.EmpresaId AND b.BodegaId=r.BodegaId LEFT JOIN inv.Articulo a ON a.EmpresaId=r.EmpresaId AND a.ArticuloId=r.ArticuloId WHERE r.EmpresaId=@E ORDER BY r.ReconciliacionInventarioId DESC;";Add(q,"@E",SqlDbType.BigInt,e);await using var rd=await q.ExecuteReaderAsync(ct);var rows=new List<ReconciliationListResponse>();while(await rd.ReadAsync(ct))rows.Add(new(rd.GetInt64(0),rd.GetString(1),rd.GetInt32(2),rd.IsDBNull(3)?null:rd.GetString(3),rd.IsDBNull(4)?null:rd.GetString(4),rd.GetDateTime(5)));return rows;}
    public async Task<IReadOnlyList<ReversibleMovementResponse>> GetReversibleMovementsAsync(long e,CancellationToken ct){await using var c=await connections.OpenAsync(e,false,ct);await using var q=c.CreateCommand();q.CommandText="SELECT TOP(200)m.MovimientoInventarioId,m.FechaContable,m.TipoMovimiento,m.NumeroDocumento,b.Nombre,a.Codigo,a.Descripcion,m.CantidadEntrada,m.CantidadSalida,m.ValorMovimiento,CAST(CASE WHEN rv.ReversionMovimientoInventarioId IS NULL THEN 0 ELSE 1 END AS bit) FROM inv.MovimientoInventario m JOIN inv.Bodega b ON b.EmpresaId=m.EmpresaId AND b.BodegaId=m.BodegaId JOIN inv.Articulo a ON a.EmpresaId=m.EmpresaId AND a.ArticuloId=m.ArticuloId LEFT JOIN inv.ReversionMovimientoInventario rv ON rv.EmpresaId=m.EmpresaId AND rv.MovimientoOriginalId=m.MovimientoInventarioId WHERE m.EmpresaId=@E ORDER BY m.MovimientoInventarioId DESC;";Add(q,"@E",SqlDbType.BigInt,e);await using var r=await q.ExecuteReaderAsync(ct);var rows=new List<ReversibleMovementResponse>();while(await r.ReadAsync(ct))rows.Add(new(r.GetInt64(0),DateOnly.FromDateTime(r.GetDateTime(1)),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetString(6),r.GetDecimal(7),r.GetDecimal(8),r.GetDecimal(9),r.GetBoolean(10)));return rows;}
    public async Task<IReadOnlyList<AuditEventResponse>> GetAuditAsync(long e,CancellationToken ct){await using var c=await connections.OpenAsync(e,false,ct);await using var q=c.CreateCommand();q.CommandText="SELECT TOP(200)x.EventoAuditoriaId,x.FechaEnUtc,x.Operacion,x.Entidad,x.EntidadId,x.DocumentoNumero,u.NombreCompleto,x.Motivo FROM audit.Evento x LEFT JOIN seg.Usuario u ON u.UsuarioId=x.UsuarioId WHERE x.EmpresaId=@E AND (x.AplicacionOrigen IN('INVENTARIO','COSTOS') OR x.Entidad LIKE 'inv.%' OR x.Entidad LIKE 'cost.%') ORDER BY x.EventoAuditoriaId DESC;";Add(q,"@E",SqlDbType.BigInt,e);await using var r=await q.ExecuteReaderAsync(ct);var rows=new List<AuditEventResponse>();while(await r.ReadAsync(ct))rows.Add(new(r.GetInt64(0),r.GetDateTime(1),r.GetString(2),r.GetString(3),r.IsDBNull(4)?null:r.GetString(4),r.IsDBNull(5)?null:r.GetString(5),r.IsDBNull(6)?null:r.GetString(6),r.IsDBNull(7)?null:r.GetString(7)));return rows;}

    private async Task<CountStateResponse> ExecuteCountProcedureAsync(long e,long id,string procedure,long? user,string? approvals,CancellationToken ct){await using var c=await connections.OpenAsync(e,false,ct);await using var q=c.CreateCommand();q.CommandType=CommandType.StoredProcedure;q.CommandText=procedure;Add(q,"@EmpresaId",SqlDbType.BigInt,e);Add(q,"@ConteoFisicoId",SqlDbType.BigInt,id);if(approvals is not null)Add(q,"@AprobacionesJson",SqlDbType.NVarChar,approvals,-1);Add(q,"@UsuarioId",SqlDbType.BigInt,user);await using var r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))throw new InvalidOperationException("El conteo no devolvio resultado.");return new(r.GetInt64(0),r.GetString(1),r.FieldCount>2&&!r.IsDBNull(2)?r.GetBoolean(2):null);}
    private static void Add(SqlCommand c,string n,SqlDbType t,object? v,int size=0){var p=size==0?new SqlParameter(n,t):new SqlParameter(n,t,size);p.Value=v??DBNull.Value;c.Parameters.Add(p);}
    private static void AddDecimal(SqlCommand c,string n,decimal v,byte precision,byte scale)=>c.Parameters.Add(new SqlParameter(n,SqlDbType.Decimal){Precision=precision,Scale=scale,Value=v});
    private static void AddDecimalNullable(SqlCommand c,string n,decimal? v,byte precision,byte scale)=>c.Parameters.Add(new SqlParameter(n,SqlDbType.Decimal){Precision=precision,Scale=scale,Value=v is null?DBNull.Value:v.Value});
}
